"
An abstract superclass representing an expression node of a source code.
"
Class {
	#name : #FASTFortranCharacterExpression,
	#superclass : #FASTFortranExpression,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranCharacterExpression class >> annotation [

	<FMClass: #CharacterExpression super: #FASTFortranExpression>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
