"
I represent Fortran Arithmetic Double Complex Literal (Constant) statement
"
Class {
	#name : #FASTFortranDoubleComplexLiteral,
	#superclass : #FASTFortranArithmeticLiteral,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranDoubleComplexLiteral class >> annotation [

	<FMClass: #DoubleComplexLiteral super: #FASTFortranArithmeticLiteral>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
