"
I represent Fortran Arithmetic Integer Literal (Constant) statement
"
Class {
	#name : #FASTFortranIntegerLiteral,
	#superclass : #FASTFortranArithmeticLiteral,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranIntegerLiteral class >> annotation [

	<FMClass: #IntegerLiteral super: #FASTFortranArithmeticLiteral>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
