"
I represent Fortran Arithmetic Complex Literal (Constant) statement
"
Class {
	#name : #FASTFortranComplexLiteral,
	#superclass : #FASTFortranArithmeticLiteral,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranComplexLiteral class >> annotation [

	<FMClass: #ComplexLiteral super: #FASTFortranArithmeticLiteral>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
