"
I represent Fortran Arithmetic Complex Literal (Constant) statement
"
Class {
	#name : #FASTFortranComplexLiteral,
	#superclass : #FASTFortranAbstractLiteral,
	#traits : 'FASTFortranTNumericalLiteral',
	#classTraits : 'FASTFortranTNumericalLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranComplexLiteral class >> annotation [

	<FMClass: #ComplexLiteral super: #FASTFortranAbstractLiteral>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
