"
An undefined object literal
"
Trait {
	#name : #FASTFortranTNullPointerLiteral,
	#traits : 'FASTFortranTLiteral',
	#classTraits : 'FASTFortranTLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Traits'
}

{ #category : #meta }
FASTFortranTNullPointerLiteral classSide >> annotation [

	<FMClass: #TNullPointerLiteral super: #Object>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
