"
I represent an Ampersand Character Literal (Constant) that is often used in parameters and format identifiers
"
Class {
	#name : #FASTFortranAmpersand,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTCharacterLiteral',
	#classTraits : 'FASTFortranTCharacterLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #'as yet unclassified' }
FASTFortranAmpersand class >> annotation [

	<FMClass: #Ampersand super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
