"
I represent Fortran Character Literal (Constant) statement
"
Class {
	#name : #FASTFortranCharacterLiteral,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTCharacterLiteral',
	#classTraits : 'FASTFortranTCharacterLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranCharacterLiteral class >> annotation [

	<FMClass: #CharacterLiteral super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
