"
I represent Fortran Equivalence statement
"
Class {
	#name : #FASTFortranEquivalenceStatement,
	#superclass : #FASTFortranAbstractStatement,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranEquivalenceStatement class >> annotation [

	<FMClass: #EquivalenceStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
