"
I represent Fortran Boolean Literal (Constant) statement
"
Class {
	#name : #FASTFortranBooleanLiteral,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTBooleanLiteral',
	#classTraits : 'FASTFortranTBooleanLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #'as yet unclassified' }
FASTFortranBooleanLiteral class >> annotation [

	<FMClass: #BooleanLiteral super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
