"
I represent Fortran Arithmetic Double Precision Literal (Constant) statement
"
Class {
	#name : #FASTFortranDoublePrecisionLiteral,
	#superclass : #FASTFortranAbstractExpression,
	#traits : 'FASTFortranTNumericalLiteral',
	#classTraits : 'FASTFortranTNumericalLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranDoublePrecisionLiteral class >> annotation [

	<FMClass: #DoublePrecisionLiteral super: #FASTFortranAbstractExpression>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
