"
I represent a range of characters in an Implicit statement
"
Class {
	#name : #FASTFortranImplicitRange,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTImplicitCharacter',
	#classTraits : 'FASTFortranTImplicitCharacter classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranImplicitRange class >> annotation [

	<FMClass: #ImplicitRange super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
