"
I represent a fortran statement with a label
"
Trait {
	#name : #FASTFortranTtFortranLabelledStatement,
	#traits : 'FASTFortranTStatement',
	#classTraits : 'FASTFortranTStatement classTrait',
	#category : #'FAST-Fortran-Entities-Traits'
}

{ #category : #meta }
FASTFortranTtFortranLabelledStatement classSide >> annotation [

	<FMClass: #TtFortranLabelledStatement super: #Object>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
