"
I represent Fortran Arithmetic Double Precision Literal (Constant) statement
"
Class {
	#name : #FASTFortranDoublePrecisionLiteral,
	#superclass : #FASTFortranArithmeticLiteral,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranDoublePrecisionLiteral class >> annotation [

	<FMClass: #DoublePrecisionLiteral super: #FASTFortranArithmeticLiteral>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
