"
The BLOCK DATA statement identifies a subprogram that initializes variables and arrays in labeled common blocks.


"
Class {
	#name : #FASTFortranBlockData,
	#superclass : #FASTFortranSubprogram,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranBlockData class >> annotation [

	<FMClass: #BlockData super: #FASTFortranSubprogram>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
