"
I represent Fortran Intrinsic statement
"
Class {
	#name : #FASTFortranIntrinsicStatement,
	#superclass : #FASTFortranAbstractStatement,
	#traits : 'FASTFortranTVariableGroup',
	#classTraits : 'FASTFortranTVariableGroup classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranIntrinsicStatement class >> annotation [

	<FMClass: #IntrinsicStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
