"
I represent Fortran Format statement
"
Class {
	#name : #FASTFortranFormatStatement,
	#superclass : #FASTFortranStatement,
	#traits : 'FASTFortranTFormatIdentifier',
	#classTraits : 'FASTFortranTFormatIdentifier classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranFormatStatement class >> annotation [

	<FMClass: #FormatStatement super: #FASTFortranStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
