"
A character literal
"
Trait {
	#name : #FASTFortranTCharacterLiteral,
	#traits : 'FASTFortranTLiteral',
	#classTraits : 'FASTFortranTLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Traits'
}

{ #category : #'as yet unclassified' }
FASTFortranTCharacterLiteral classSide >> annotation [

	<FMClass: #TCharacterLiteral super: #Object>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
