"
I represent Fortran Go To (Unconditional) statement
"
Class {
	#name : #FASTFortranGoToUnconditionalStatement,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTLabelledStatement',
	#classTraits : 'FASTFortranTLabelledStatement classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranGoToUnconditionalStatement class >> annotation [

	<FMClass: #GoToUnconditionalStatement super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
