"
I represent Fortran Go To (Computed) statement
"
Class {
	#name : #FASTFortranGoToComputedStatement,
	#superclass : #FASTFortranAbstractStatement,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranGoToComputedStatement class >> annotation [

	<FMClass: #GoToComputedStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
