"
I represent an Ampersand Character Literal (Constant) that is often used in parameters and format identifiers
"
Class {
	#name : #FASTFortranAmpersand,
	#superclass : #FASTFortranCharacterLiteral,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranAmpersand class >> annotation [

	<FMClass: #Ampersand super: #FASTFortranCharacterLiteral>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
