"
I represent Fortran Go To (Unconditional) statement
"
Class {
	#name : #FASTFortranGoToUnconditionalStatement,
	#superclass : #FASTFortranStatement,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranGoToUnconditionalStatement class >> annotation [

	<FMClass: #GoToUnconditionalStatement super: #FASTFortranStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
