"
I represent Fortran Arithmetic Double Complex Literal (Constant) statement
"
Class {
	#name : #FASTFortranDoubleComplexLiteral,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTNumericalLiteral',
	#classTraits : 'FASTFortranTNumericalLiteral classTrait',
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranDoubleComplexLiteral class >> annotation [

	<FMClass: #DoubleComplexLiteral super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
